apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - image: harsha6798/ci_cd_practicals_java_image:1
          name:  java-app
          ports:
          - containerPort: 8080
       
    
